tschiang23/twitter-api-2020

middleware/auth.js
routes/modules/user.js

feat:add auth middleware

---

controllers/adminController.js
routes/index.js
routes/modules/admin.js

feat:add admin login

---

controllers/followshipController.js
routes/modules/followship.js

使用者能在首頁的側邊欄，看見跟隨者 (followers) 數量排列前 10 的推薦跟隨名單

feat: sidebar top followings

---

config/passport.js

add JwtStrategy requires secret

add JwtStrategy requires secret

---

seeders/20230601102119-users-seed-file.js

feat: add more users

---

controllers/tweetController.js
middleware/auth.js

fix: error code

---

controllers/adminController.js

fix: table name

---

controllers/userController.js

modify status code

---

controllers/adminController.js

refactor: remove admin attributes

---

seeders/20230612082611-likes-seed-file.js
seeders/20230612090028-followships-seed-file.js

添加LIikes表的種子資料
添加Followships表的種子資料

feat: add likes and followships

---

controllers/userController.js
routes/modules/user.js

modify patch to update user account

modify patch to update user account

---

controllers/followshipController.js
controllers/tweetController.js

fix: naming

---

controllers/tweetController.js

重構POST兩隻路由的message, 前端需要即時渲染資料

fix :postTweet and postReply message

---

controllers/followshipController.js

feat: get param id

---

controllers/userController.js

modify sigin user data

---

controllers/userController.js

fix: update user account

---

controllers/userController.js

feat: add userId

---

controllers/tweetController.js

fix: sorting for tweet createdAt

---

controllers/userController.js

feat:add check user exists

---

controllers/followshipController.js
controllers/tweetController.js
middleware/auth.js

unify name  and status code

---

controllers/userController.js
middleware/validator.js

feat:add check user validator

---

middleware/validator.js

refactor:change display message

refactor:change display message

---

controllers/userController.js
middleware/auth.js

modify login and update user data format

---

README.md

feat: add some info

---

controllers/userController.js

fix:get user following

---

app.js

feat:add cors options

---

app.js

feat:add corsOptions

---

app.js

add allowheaders

---

controllers/adminController.js

fix:delete tweet issue
